version: 1.{build}
image: Visual Studio 2019
configuration: Release
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.3.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
build:
  verbosity: minimal
before_build:
  - nuget restore
artifacts:
- path: '\NotEnoughAV1Encodes\bin\Release\'
  name: NotEnoughAV1Encodes.exe
skip_commits:
  files:
    - README.md
