//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotEnoughAV1Encodes.resources.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NotEnoughAV1Encodes.resources.lang.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like 7-zip is not downloaded.
        ///
        ///Please download and extract 7-zip to the following path:
        ///
        ///.
        /// </summary>
        public static string _7ZipNotDetectedMessage {
            get {
                return ResourceManager.GetString("7ZipNotDetectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7-zip not detected!.
        /// </summary>
        public static string _7ZipNotDetectedTitle {
            get {
                return ResourceManager.GetString("7ZipNotDetectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ButtonDeletePreset {
            get {
                return ResourceManager.GetString("ButtonDeletePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Item.
        /// </summary>
        public static string ButtonEditSelectedItem {
            get {
                return ResourceManager.GetString("ButtonEditSelectedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Exit.
        /// </summary>
        public static string ButtonExit {
            get {
                return ResourceManager.GetString("ButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➔ Batch Folder.
        /// </summary>
        public static string ButtonOpenBatchFolder {
            get {
                return ResourceManager.GetString("ButtonOpenBatchFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➔ Project File.
        /// </summary>
        public static string ButtonOpenProjectFile {
            get {
                return ResourceManager.GetString("ButtonOpenProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➔ Single File.
        /// </summary>
        public static string ButtonOpenVideoFile {
            get {
                return ResourceManager.GetString("ButtonOpenVideoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Item.
        /// </summary>
        public static string ButtonRemoveSelectedQueueItem {
            get {
                return ResourceManager.GetString("ButtonRemoveSelectedQueueItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ButtonResetBGImage {
            get {
                return ResourceManager.GetString("ButtonResetBGImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonSavePreset {
            get {
                return ResourceManager.GetString("ButtonSavePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string ButtonSelectBGImage {
            get {
                return ResourceManager.GetString("ButtonSelectBGImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as Default.
        /// </summary>
        public static string ButtonSetPresetDefault {
            get {
                return ResourceManager.GetString("ButtonSetPresetDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Settings.
        /// </summary>
        public static string ButtonTestSettings {
            get {
                return ResourceManager.GetString("ButtonTestSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updater.
        /// </summary>
        public static string ButtonUpdater {
            get {
                return ResourceManager.GetString("ButtonUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Settings.
        /// </summary>
        public static string CheckBoxCustomVideoSettings {
            get {
                return ResourceManager.GetString("CheckBoxCustomVideoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realtime Mode.
        /// </summary>
        public static string CheckBoxRealTimeMode {
            get {
                return ResourceManager.GetString("CheckBoxRealTimeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-Pass encoding.
        /// </summary>
        public static string CheckBoxTwoPassEncoding {
            get {
                return ResourceManager.GetString("CheckBoxTwoPassEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Image.
        /// </summary>
        public static string GroupBoxBackroundImage {
            get {
                return ResourceManager.GetString("GroupBoxBackroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop.
        /// </summary>
        public static string GroupBoxCrop {
            get {
                return ResourceManager.GetString("GroupBoxCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Encoding Settings.
        /// </summary>
        public static string GroupBoxCurrentSettings {
            get {
                return ResourceManager.GetString("GroupBoxCurrentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deinterlace.
        /// </summary>
        public static string GroupBoxDeinterlace {
            get {
                return ResourceManager.GetString("GroupBoxDeinterlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input / Output.
        /// </summary>
        public static string GroupBoxInputOutput {
            get {
                return ResourceManager.GetString("GroupBoxInputOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string GroupBoxLanguage {
            get {
                return ResourceManager.GetString("GroupBoxLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimization.
        /// </summary>
        public static string GroupBoxOptimization {
            get {
                return ResourceManager.GetString("GroupBoxOptimization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presets.
        /// </summary>
        public static string GroupBoxPresets {
            get {
                return ResourceManager.GetString("GroupBoxPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string GroupBoxQuality {
            get {
                return ResourceManager.GetString("GroupBoxQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize.
        /// </summary>
        public static string GroupBoxResize {
            get {
                return ResourceManager.GetString("GroupBoxResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        public static string GroupBoxRotate {
            get {
                return ResourceManager.GetString("GroupBoxRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Settings.
        /// </summary>
        public static string GroupBoxThemeSettings {
            get {
                return ResourceManager.GetString("GroupBoxThemeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Container.
        /// </summary>
        public static string GroupBoxVideoContainer {
            get {
                return ResourceManager.GetString("GroupBoxVideoContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Information.
        /// </summary>
        public static string GroupBoxVideoInformation {
            get {
                return ResourceManager.GetString("GroupBoxVideoInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workers and Splitting.
        /// </summary>
        public static string GroupBoxWorkersAndSplitting {
            get {
                return ResourceManager.GetString("GroupBoxWorkersAndSplitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDR Settings.
        /// </summary>
        public static string HDRSettings {
            get {
                return ResourceManager.GetString("HDRSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent Theme:.
        /// </summary>
        public static string LabelAccentTheme {
            get {
                return ResourceManager.GetString("LabelAccentTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Queue.
        /// </summary>
        public static string LabelAddToQueue {
            get {
                return ResourceManager.GetString("LabelAddToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {filename} = Input Filename.
        /// </summary>
        public static string LabelAvailableBatchFilename {
            get {
                return ResourceManager.GetString("LabelAvailableBatchFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {presetname} = Name of Preset.
        /// </summary>
        public static string LabelAvailableBatchPresetName {
            get {
                return ResourceManager.GetString("LabelAvailableBatchPresetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Theme:.
        /// </summary>
        public static string LabelBaseTheme {
            get {
                return ResourceManager.GetString("LabelBaseTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Filename:.
        /// </summary>
        public static string LabelBatchFileName {
            get {
                return ResourceManager.GetString("LabelBatchFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit-Depth:.
        /// </summary>
        public static string LabelBitDepth {
            get {
                return ResourceManager.GetString("LabelBitDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitrate (kbps):.
        /// </summary>
        public static string LabelBitrate {
            get {
                return ResourceManager.GetString("LabelBitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitrate (avg):.
        /// </summary>
        public static string LabelBitrateAvg {
            get {
                return ResourceManager.GetString("LabelBitrateAvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitrate (max):.
        /// </summary>
        public static string LabelBitrateMax {
            get {
                return ResourceManager.GetString("LabelBitrateMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitrate (min):.
        /// </summary>
        public static string LabelBitrateMin {
            get {
                return ResourceManager.GetString("LabelBitrateMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string LabelBottom {
            get {
                return ResourceManager.GetString("LabelBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builds provided by jeremylee.sh under GPLv3.
        /// </summary>
        public static string LabelBuildsProvidedBy {
            get {
                return ResourceManager.GetString("LabelBuildsProvidedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burn in:.
        /// </summary>
        public static string LabelBurnIn {
            get {
                return ResourceManager.GetString("LabelBurnIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LabelCancel {
            get {
                return ResourceManager.GetString("LabelCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels:.
        /// </summary>
        public static string LabelChannels {
            get {
                return ResourceManager.GetString("LabelChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chunk Length (seconds):.
        /// </summary>
        public static string LabelChunkLength {
            get {
                return ResourceManager.GetString("LabelChunkLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codec:.
        /// </summary>
        public static string LabelCodec {
            get {
                return ResourceManager.GetString("LabelCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Format:.
        /// </summary>
        public static string LabelColorFormat {
            get {
                return ResourceManager.GetString("LabelColorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container:.
        /// </summary>
        public static string LabelContainer {
            get {
                return ResourceManager.GetString("LabelContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default:.
        /// </summary>
        public static string LabelDefault {
            get {
                return ResourceManager.GetString("LabelDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Audio Behavior.
        /// </summary>
        public static string LabelDefaultAudioBehavior {
            get {
                return ResourceManager.GetString("LabelDefaultAudioBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Output Location.
        /// </summary>
        public static string LabelDefaultOutputLocation {
            get {
                return ResourceManager.GetString("LabelDefaultOutputLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deinterlace:.
        /// </summary>
        public static string LabelDeinterlace {
            get {
                return ResourceManager.GetString("LabelDeinterlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string LabelDestination {
            get {
                return ResourceManager.GetString("LabelDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode Queue Parallel instead of chunking:.
        /// </summary>
        public static string LabelEncodeQueueParallel {
            get {
                return ResourceManager.GetString("LabelEncodeQueueParallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoder:.
        /// </summary>
        public static string LabelEncoder {
            get {
                return ResourceManager.GetString("LabelEncoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framerate:.
        /// </summary>
        public static string LabelFramerate {
            get {
                return ResourceManager.GetString("LabelFramerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        public static string LabelHeight {
            get {
                return ResourceManager.GetString("LabelHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons:.
        /// </summary>
        public static string LabelIcons {
            get {
                return ResourceManager.GetString("LabelIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string LabelLanguage {
            get {
                return ResourceManager.GetString("LabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string LabelLeft {
            get {
                return ResourceManager.GetString("LabelLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length:.
        /// </summary>
        public static string LabelLength {
            get {
                return ResourceManager.GetString("LabelLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method for opening a source..
        /// </summary>
        public static string LabelMethodOpeningSource {
            get {
                return ResourceManager.GetString("LabelMethodOpeningSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Audio Found.
        /// </summary>
        public static string LabelNoAudioFound {
            get {
                return ResourceManager.GetString("LabelNoAudioFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Subtitle Found.
        /// </summary>
        public static string LabelNoSubtitleFound {
            get {
                return ResourceManager.GetString("LabelNoSubtitleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset:.
        /// </summary>
        public static string LabelPreset {
            get {
                return ResourceManager.GetString("LabelPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset Name:.
        /// </summary>
        public static string LabelPresetName {
            get {
                return ResourceManager.GetString("LabelPresetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Priority:.
        /// </summary>
        public static string LabelProcessPriority {
            get {
                return ResourceManager.GetString("LabelProcessPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Mode:.
        /// </summary>
        public static string LabelQualityMode {
            get {
                return ResourceManager.GetString("LabelQualityMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantizer:.
        /// </summary>
        public static string LabelQuantizer {
            get {
                return ResourceManager.GetString("LabelQuantizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reencode Method:.
        /// </summary>
        public static string LabelReencodeMethod {
            get {
                return ResourceManager.GetString("LabelReencodeMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution:.
        /// </summary>
        public static string LabelResolution {
            get {
                return ResourceManager.GetString("LabelResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string LabelRight {
            get {
                return ResourceManager.GetString("LabelRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate (Clockwise):.
        /// </summary>
        public static string LabelRotate {
            get {
                return ResourceManager.GetString("LabelRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm:.
        /// </summary>
        public static string LabelScalingAlgorithm {
            get {
                return ResourceManager.GetString("LabelScalingAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Preset for encoding:.
        /// </summary>
        public static string LabelSelectPresetForEncoding {
            get {
                return ResourceManager.GetString("LabelSelectPresetForEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string LabelSource {
            get {
                return ResourceManager.GetString("LabelSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string LabelSpeed {
            get {
                return ResourceManager.GetString("LabelSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitting Method:.
        /// </summary>
        public static string LabelSplittingMethod {
            get {
                return ResourceManager.GetString("LabelSplittingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string LabelStartPauseButton {
            get {
                return ResourceManager.GetString("LabelStartPauseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string LabelStatus {
            get {
                return ResourceManager.GetString("LabelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp Path.
        /// </summary>
        public static string LabelTempPath {
            get {
                return ResourceManager.GetString("LabelTempPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        public static string LabelTheme {
            get {
                return ResourceManager.GetString("LabelTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold:.
        /// </summary>
        public static string LabelThreshold {
            get {
                return ResourceManager.GetString("LabelThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string LabelTop {
            get {
                return ResourceManager.GetString("LabelTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Name:.
        /// </summary>
        public static string LabelTrackName {
            get {
                return ResourceManager.GetString("LabelTrackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string LabelVersion {
            get {
                return ResourceManager.GetString("LabelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Destination Selected.
        /// </summary>
        public static string LabelVideoDestination {
            get {
                return ResourceManager.GetString("LabelVideoDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination:.
        /// </summary>
        public static string LabelVideoDestination1 {
            get {
                return ResourceManager.GetString("LabelVideoDestination1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Source Selected.
        /// </summary>
        public static string LabelVideoSource {
            get {
                return ResourceManager.GetString("LabelVideoSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        public static string LabelVideoSource1 {
            get {
                return ResourceManager.GetString("LabelVideoSource1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width:.
        /// </summary>
        public static string LabelWidth {
            get {
                return ResourceManager.GetString("LabelWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker Count:.
        /// </summary>
        public static string LabelWorkerCount {
            get {
                return ResourceManager.GetString("LabelWorkerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEAV1E currently does not support Constrained Bitrate (aomenc).
        /// </summary>
        public static string MessageConstrainedBitrateAomenc {
            get {
                return ResourceManager.GetString("MessageConstrainedBitrateAomenc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please create a Preset before adding batch files..
        /// </summary>
        public static string MessageCreatePresetBeforeBatch {
            get {
                return ResourceManager.GetString("MessageCreatePresetBeforeBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Input selected!.
        /// </summary>
        public static string MessageNoInput {
            get {
                return ResourceManager.GetString("MessageNoInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Output selected!.
        /// </summary>
        public static string MessageNoOutput {
            get {
                return ResourceManager.GetString("MessageNoOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEAV1E currently only supports Constant Quality or Bitrate Mode (rav1e / svt-av1).
        /// </summary>
        public static string MessageQualityModeRav1eSVT {
            get {
                return ResourceManager.GetString("MessageQualityModeRav1eSVT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue is empty! \nPlease add your job to the Queue..
        /// </summary>
        public static string MessageQueueEmpty {
            get {
                return ResourceManager.GetString("MessageQueueEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ProgramSettings {
            get {
                return ResourceManager.GetString("ProgramSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st Pass:.
        /// </summary>
        public static string Queue1stPass {
            get {
                return ResourceManager.GetString("Queue1stPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd Pass:.
        /// </summary>
        public static string Queue2ndPass {
            get {
                return ResourceManager.GetString("Queue2ndPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string QueueMenuItemEdit {
            get {
                return ResourceManager.GetString("QueueMenuItemEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Destination.
        /// </summary>
        public static string QueueMenuItemOpenOutputDir {
            get {
                return ResourceManager.GetString("QueueMenuItemOpenOutputDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min left.
        /// </summary>
        public static string QueueMinLeft {
            get {
                return ResourceManager.GetString("QueueMinLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string TabItemAdvanced {
            get {
                return ResourceManager.GetString("TabItemAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string TabItemAudio {
            get {
                return ResourceManager.GetString("TabItemAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string TabItemFilters {
            get {
                return ResourceManager.GetString("TabItemFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string TabItemQueue {
            get {
                return ResourceManager.GetString("TabItemQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitles.
        /// </summary>
        public static string TabItemSubtitles {
            get {
                return ResourceManager.GetString("TabItemSubtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string TabItemSummary {
            get {
                return ResourceManager.GetString("TabItemSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string TabItemVideo {
            get {
                return ResourceManager.GetString("TabItemVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Destination Selected.
        /// </summary>
        public static string TextBoxDestination {
            get {
                return ResourceManager.GetString("TextBoxDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Subtitles.
        /// </summary>
        public static string ToggleSwitchActivateSubtitles {
            get {
                return ResourceManager.GetString("ToggleSwitchActivateSubtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Settings.
        /// </summary>
        public static string ToggleSwitchAdvancedSettings {
            get {
                return ResourceManager.GetString("ToggleSwitchAdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Pause / Resume.
        /// </summary>
        public static string ToggleSwitchAutoPauseResume {
            get {
                return ResourceManager.GetString("ToggleSwitchAutoPauseResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically Pauses and Resumes Encoding if System is IDLE for more than 1 minute.
        /// </summary>
        public static string ToggleSwitchAutoPauseResumeTooltip {
            get {
                return ResourceManager.GetString("ToggleSwitchAutoPauseResumeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Temp Files.
        /// </summary>
        public static string ToggleSwitchDeleteTempFiles {
            get {
                return ResourceManager.GetString("ToggleSwitchDeleteTempFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Input Seeking.
        /// </summary>
        public static string ToggleSwitchInputSeeking {
            get {
                return ResourceManager.GetString("ToggleSwitchInputSeeking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string ToggleSwitchLogging {
            get {
                return ResourceManager.GetString("ToggleSwitchLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override Worker Count.
        /// </summary>
        public static string ToggleSwitchOverrideWorkerCount {
            get {
                return ResourceManager.GetString("ToggleSwitchOverrideWorkerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown After Encode.
        /// </summary>
        public static string ToggleSwitchShutdown {
            get {
                return ResourceManager.GetString("ToggleSwitchShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Bit-Depth from Preset?.
        /// </summary>
        public static string ToggleSwitchUsePresetBitDepth {
            get {
                return ResourceManager.GetString("ToggleSwitchUsePresetBitDepth", resourceCulture);
            }
        }
    }
}
