//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotEnoughAV1Encodes.resources.lang {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NotEnoughAV1Encodes.resources.lang.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string ButtonDeletePreset {
            get {
                return ResourceManager.GetString("ButtonDeletePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Item ähnelt.
        /// </summary>
        public static string ButtonEditSelectedItem {
            get {
                return ResourceManager.GetString("ButtonEditSelectedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save and Exit ähnelt.
        /// </summary>
        public static string ButtonExit {
            get {
                return ResourceManager.GetString("ButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ➔ Batch Folder ähnelt.
        /// </summary>
        public static string ButtonOpenBatchFolder {
            get {
                return ResourceManager.GetString("ButtonOpenBatchFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ➔ Project File ähnelt.
        /// </summary>
        public static string ButtonOpenProjectFile {
            get {
                return ResourceManager.GetString("ButtonOpenProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ➔ Single File ähnelt.
        /// </summary>
        public static string ButtonOpenVideoFile {
            get {
                return ResourceManager.GetString("ButtonOpenVideoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove Item ähnelt.
        /// </summary>
        public static string ButtonRemoveSelectedQueueItem {
            get {
                return ResourceManager.GetString("ButtonRemoveSelectedQueueItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset ähnelt.
        /// </summary>
        public static string ButtonResetBGImage {
            get {
                return ResourceManager.GetString("ButtonResetBGImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string ButtonSavePreset {
            get {
                return ResourceManager.GetString("ButtonSavePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select ähnelt.
        /// </summary>
        public static string ButtonSelectBGImage {
            get {
                return ResourceManager.GetString("ButtonSelectBGImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set as Default ähnelt.
        /// </summary>
        public static string ButtonSetPresetDefault {
            get {
                return ResourceManager.GetString("ButtonSetPresetDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test Settings ähnelt.
        /// </summary>
        public static string ButtonTestSettings {
            get {
                return ResourceManager.GetString("ButtonTestSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Updater ähnelt.
        /// </summary>
        public static string ButtonUpdater {
            get {
                return ResourceManager.GetString("ButtonUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom Settings ähnelt.
        /// </summary>
        public static string CheckBoxCustomVideoSettings {
            get {
                return ResourceManager.GetString("CheckBoxCustomVideoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Realtime Mode ähnelt.
        /// </summary>
        public static string CheckBoxRealTimeMode {
            get {
                return ResourceManager.GetString("CheckBoxRealTimeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2-Pass encoding ähnelt.
        /// </summary>
        public static string CheckBoxTwoPassEncoding {
            get {
                return ResourceManager.GetString("CheckBoxTwoPassEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Background Image ähnelt.
        /// </summary>
        public static string GroupBoxBackroundImage {
            get {
                return ResourceManager.GetString("GroupBoxBackroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crop ähnelt.
        /// </summary>
        public static string GroupBoxCrop {
            get {
                return ResourceManager.GetString("GroupBoxCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current Encoding Settings ähnelt.
        /// </summary>
        public static string GroupBoxCurrentSettings {
            get {
                return ResourceManager.GetString("GroupBoxCurrentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deinterlace ähnelt.
        /// </summary>
        public static string GroupBoxDeinterlace {
            get {
                return ResourceManager.GetString("GroupBoxDeinterlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input / Output ähnelt.
        /// </summary>
        public static string GroupBoxInputOutput {
            get {
                return ResourceManager.GetString("GroupBoxInputOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        public static string GroupBoxLanguage {
            get {
                return ResourceManager.GetString("GroupBoxLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Optimization ähnelt.
        /// </summary>
        public static string GroupBoxOptimization {
            get {
                return ResourceManager.GetString("GroupBoxOptimization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Presets ähnelt.
        /// </summary>
        public static string GroupBoxPresets {
            get {
                return ResourceManager.GetString("GroupBoxPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quality ähnelt.
        /// </summary>
        public static string GroupBoxQuality {
            get {
                return ResourceManager.GetString("GroupBoxQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resize ähnelt.
        /// </summary>
        public static string GroupBoxResize {
            get {
                return ResourceManager.GetString("GroupBoxResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rotate ähnelt.
        /// </summary>
        public static string GroupBoxRotate {
            get {
                return ResourceManager.GetString("GroupBoxRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Theme Settings ähnelt.
        /// </summary>
        public static string GroupBoxThemeSettings {
            get {
                return ResourceManager.GetString("GroupBoxThemeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Video Container ähnelt.
        /// </summary>
        public static string GroupBoxVideoContainer {
            get {
                return ResourceManager.GetString("GroupBoxVideoContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Video Information ähnelt.
        /// </summary>
        public static string GroupBoxVideoInformation {
            get {
                return ResourceManager.GetString("GroupBoxVideoInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Workers and Splitting ähnelt.
        /// </summary>
        public static string GroupBoxWorkersAndSplitting {
            get {
                return ResourceManager.GetString("GroupBoxWorkersAndSplitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accent Theme: ähnelt.
        /// </summary>
        public static string LabelAccentTheme {
            get {
                return ResourceManager.GetString("LabelAccentTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add to Queue ähnelt.
        /// </summary>
        public static string LabelAddToQueue {
            get {
                return ResourceManager.GetString("LabelAddToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {filename} = Input Filename ähnelt.
        /// </summary>
        public static string LabelAvailableBatchFilename {
            get {
                return ResourceManager.GetString("LabelAvailableBatchFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {presetname} = Name of Preset ähnelt.
        /// </summary>
        public static string LabelAvailableBatchPresetName {
            get {
                return ResourceManager.GetString("LabelAvailableBatchPresetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Base Theme: ähnelt.
        /// </summary>
        public static string LabelBaseTheme {
            get {
                return ResourceManager.GetString("LabelBaseTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Batch Filename: ähnelt.
        /// </summary>
        public static string LabelBatchFileName {
            get {
                return ResourceManager.GetString("LabelBatchFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bit-Depth: ähnelt.
        /// </summary>
        public static string LabelBitDepth {
            get {
                return ResourceManager.GetString("LabelBitDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitrate (kbps): ähnelt.
        /// </summary>
        public static string LabelBitrate {
            get {
                return ResourceManager.GetString("LabelBitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitrate (avg): ähnelt.
        /// </summary>
        public static string LabelBitrateAvg {
            get {
                return ResourceManager.GetString("LabelBitrateAvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitrate (max): ähnelt.
        /// </summary>
        public static string LabelBitrateMax {
            get {
                return ResourceManager.GetString("LabelBitrateMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitrate (min): ähnelt.
        /// </summary>
        public static string LabelBitrateMin {
            get {
                return ResourceManager.GetString("LabelBitrateMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bottom ähnelt.
        /// </summary>
        public static string LabelBottom {
            get {
                return ResourceManager.GetString("LabelBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Builds provided by jeremylee.sh under GPLv3 ähnelt.
        /// </summary>
        public static string LabelBuildsProvidedBy {
            get {
                return ResourceManager.GetString("LabelBuildsProvidedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Burn in: ähnelt.
        /// </summary>
        public static string LabelBurnIn {
            get {
                return ResourceManager.GetString("LabelBurnIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string LabelCancel {
            get {
                return ResourceManager.GetString("LabelCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Channels: ähnelt.
        /// </summary>
        public static string LabelChannels {
            get {
                return ResourceManager.GetString("LabelChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chunk Length (seconds): ähnelt.
        /// </summary>
        public static string LabelChunkLength {
            get {
                return ResourceManager.GetString("LabelChunkLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Codec: ähnelt.
        /// </summary>
        public static string LabelCodec {
            get {
                return ResourceManager.GetString("LabelCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color Format: ähnelt.
        /// </summary>
        public static string LabelColorFormat {
            get {
                return ResourceManager.GetString("LabelColorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Container: ähnelt.
        /// </summary>
        public static string LabelContainer {
            get {
                return ResourceManager.GetString("LabelContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default: ähnelt.
        /// </summary>
        public static string LabelDefault {
            get {
                return ResourceManager.GetString("LabelDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default Audio Behavior ähnelt.
        /// </summary>
        public static string LabelDefaultAudioBehavior {
            get {
                return ResourceManager.GetString("LabelDefaultAudioBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deinterlace: ähnelt.
        /// </summary>
        public static string LabelDeinterlace {
            get {
                return ResourceManager.GetString("LabelDeinterlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Destination ähnelt.
        /// </summary>
        public static string LabelDestination {
            get {
                return ResourceManager.GetString("LabelDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Encode Queue Parallel instead of chunking: ähnelt.
        /// </summary>
        public static string LabelEncodeQueueParallel {
            get {
                return ResourceManager.GetString("LabelEncodeQueueParallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Encoder: ähnelt.
        /// </summary>
        public static string LabelEncoder {
            get {
                return ResourceManager.GetString("LabelEncoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Framerate: ähnelt.
        /// </summary>
        public static string LabelFramerate {
            get {
                return ResourceManager.GetString("LabelFramerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Height: ähnelt.
        /// </summary>
        public static string LabelHeight {
            get {
                return ResourceManager.GetString("LabelHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Icons: ähnelt.
        /// </summary>
        public static string LabelIcons {
            get {
                return ResourceManager.GetString("LabelIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language: ähnelt.
        /// </summary>
        public static string LabelLanguage {
            get {
                return ResourceManager.GetString("LabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Left ähnelt.
        /// </summary>
        public static string LabelLeft {
            get {
                return ResourceManager.GetString("LabelLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Length: ähnelt.
        /// </summary>
        public static string LabelLength {
            get {
                return ResourceManager.GetString("LabelLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Method for opening a source. ähnelt.
        /// </summary>
        public static string LabelMethodOpeningSource {
            get {
                return ResourceManager.GetString("LabelMethodOpeningSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Audio Found ähnelt.
        /// </summary>
        public static string LabelNoAudioFound {
            get {
                return ResourceManager.GetString("LabelNoAudioFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Subtitle Found ähnelt.
        /// </summary>
        public static string LabelNoSubtitleFound {
            get {
                return ResourceManager.GetString("LabelNoSubtitleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preset: ähnelt.
        /// </summary>
        public static string LabelPreset {
            get {
                return ResourceManager.GetString("LabelPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preset Name: ähnelt.
        /// </summary>
        public static string LabelPresetName {
            get {
                return ResourceManager.GetString("LabelPresetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Process Priority: ähnelt.
        /// </summary>
        public static string LabelProcessPriority {
            get {
                return ResourceManager.GetString("LabelProcessPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quality Mode: ähnelt.
        /// </summary>
        public static string LabelQualityMode {
            get {
                return ResourceManager.GetString("LabelQualityMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quantizer: ähnelt.
        /// </summary>
        public static string LabelQuantizer {
            get {
                return ResourceManager.GetString("LabelQuantizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reencode Method: ähnelt.
        /// </summary>
        public static string LabelReencodeMethod {
            get {
                return ResourceManager.GetString("LabelReencodeMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resolution: ähnelt.
        /// </summary>
        public static string LabelResolution {
            get {
                return ResourceManager.GetString("LabelResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Right ähnelt.
        /// </summary>
        public static string LabelRight {
            get {
                return ResourceManager.GetString("LabelRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rotate (Clockwise): ähnelt.
        /// </summary>
        public static string LabelRotate {
            get {
                return ResourceManager.GetString("LabelRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Algorithm: ähnelt.
        /// </summary>
        public static string LabelScalingAlgorithm {
            get {
                return ResourceManager.GetString("LabelScalingAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Preset for encoding: ähnelt.
        /// </summary>
        public static string LabelSelectPresetForEncoding {
            get {
                return ResourceManager.GetString("LabelSelectPresetForEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Source ähnelt.
        /// </summary>
        public static string LabelSource {
            get {
                return ResourceManager.GetString("LabelSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speed ähnelt.
        /// </summary>
        public static string LabelSpeed {
            get {
                return ResourceManager.GetString("LabelSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Splitting Method: ähnelt.
        /// </summary>
        public static string LabelSplittingMethod {
            get {
                return ResourceManager.GetString("LabelSplittingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        public static string LabelStartPauseButton {
            get {
                return ResourceManager.GetString("LabelStartPauseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status: ähnelt.
        /// </summary>
        public static string LabelStatus {
            get {
                return ResourceManager.GetString("LabelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Temp Path ähnelt.
        /// </summary>
        public static string LabelTempPath {
            get {
                return ResourceManager.GetString("LabelTempPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Theme: ähnelt.
        /// </summary>
        public static string LabelTheme {
            get {
                return ResourceManager.GetString("LabelTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Threshold: ähnelt.
        /// </summary>
        public static string LabelThreshold {
            get {
                return ResourceManager.GetString("LabelThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Top ähnelt.
        /// </summary>
        public static string LabelTop {
            get {
                return ResourceManager.GetString("LabelTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Track Name: ähnelt.
        /// </summary>
        public static string LabelTrackName {
            get {
                return ResourceManager.GetString("LabelTrackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version: ähnelt.
        /// </summary>
        public static string LabelVersion {
            get {
                return ResourceManager.GetString("LabelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Destination Selected ähnelt.
        /// </summary>
        public static string LabelVideoDestination {
            get {
                return ResourceManager.GetString("LabelVideoDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Destination: ähnelt.
        /// </summary>
        public static string LabelVideoDestination1 {
            get {
                return ResourceManager.GetString("LabelVideoDestination1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Source Selected ähnelt.
        /// </summary>
        public static string LabelVideoSource {
            get {
                return ResourceManager.GetString("LabelVideoSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Source: ähnelt.
        /// </summary>
        public static string LabelVideoSource1 {
            get {
                return ResourceManager.GetString("LabelVideoSource1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Width: ähnelt.
        /// </summary>
        public static string LabelWidth {
            get {
                return ResourceManager.GetString("LabelWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Worker Count: ähnelt.
        /// </summary>
        public static string LabelWorkerCount {
            get {
                return ResourceManager.GetString("LabelWorkerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NEAV1E currently does not support Constrained Bitrate (aomenc) ähnelt.
        /// </summary>
        public static string MessageConstrainedBitrateAomenc {
            get {
                return ResourceManager.GetString("MessageConstrainedBitrateAomenc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please create a Preset before adding batch files. ähnelt.
        /// </summary>
        public static string MessageCreatePresetBeforeBatch {
            get {
                return ResourceManager.GetString("MessageCreatePresetBeforeBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Input selected! ähnelt.
        /// </summary>
        public static string MessageNoInput {
            get {
                return ResourceManager.GetString("MessageNoInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Output selected! ähnelt.
        /// </summary>
        public static string MessageNoOutput {
            get {
                return ResourceManager.GetString("MessageNoOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NEAV1E currently only supports Constant Quality or Bitrate Mode (rav1e / svt-av1) ähnelt.
        /// </summary>
        public static string MessageQualityModeRav1eSVT {
            get {
                return ResourceManager.GetString("MessageQualityModeRav1eSVT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Queue is empty! \nPlease add your job to the Queue. ähnelt.
        /// </summary>
        public static string MessageQueueEmpty {
            get {
                return ResourceManager.GetString("MessageQueueEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pause ähnelt.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string ProgramSettings {
            get {
                return ResourceManager.GetString("ProgramSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1st Pass: ähnelt.
        /// </summary>
        public static string Queue1stPass {
            get {
                return ResourceManager.GetString("Queue1stPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2nd Pass: ähnelt.
        /// </summary>
        public static string Queue2ndPass {
            get {
                return ResourceManager.GetString("Queue2ndPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string QueueMenuItemEdit {
            get {
                return ResourceManager.GetString("QueueMenuItemEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Destination ähnelt.
        /// </summary>
        public static string QueueMenuItemOpenOutputDir {
            get {
                return ResourceManager.GetString("QueueMenuItemOpenOutputDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die min left ähnelt.
        /// </summary>
        public static string QueueMinLeft {
            get {
                return ResourceManager.GetString("QueueMinLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resume ähnelt.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advanced ähnelt.
        /// </summary>
        public static string TabItemAdvanced {
            get {
                return ResourceManager.GetString("TabItemAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Audio ähnelt.
        /// </summary>
        public static string TabItemAudio {
            get {
                return ResourceManager.GetString("TabItemAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filters ähnelt.
        /// </summary>
        public static string TabItemFilters {
            get {
                return ResourceManager.GetString("TabItemFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Queue ähnelt.
        /// </summary>
        public static string TabItemQueue {
            get {
                return ResourceManager.GetString("TabItemQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subtitles ähnelt.
        /// </summary>
        public static string TabItemSubtitles {
            get {
                return ResourceManager.GetString("TabItemSubtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Summary ähnelt.
        /// </summary>
        public static string TabItemSummary {
            get {
                return ResourceManager.GetString("TabItemSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Video ähnelt.
        /// </summary>
        public static string TabItemVideo {
            get {
                return ResourceManager.GetString("TabItemVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Destination Selected ähnelt.
        /// </summary>
        public static string TextBoxDestination {
            get {
                return ResourceManager.GetString("TextBoxDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advanced Settings ähnelt.
        /// </summary>
        public static string ToggleSwitchAdvancedSettings {
            get {
                return ResourceManager.GetString("ToggleSwitchAdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Temp Files ähnelt.
        /// </summary>
        public static string ToggleSwitchDeleteTempFiles {
            get {
                return ResourceManager.GetString("ToggleSwitchDeleteTempFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logging ähnelt.
        /// </summary>
        public static string ToggleSwitchLogging {
            get {
                return ResourceManager.GetString("ToggleSwitchLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Override Worker Count ähnelt.
        /// </summary>
        public static string ToggleSwitchOverrideWorkerCount {
            get {
                return ResourceManager.GetString("ToggleSwitchOverrideWorkerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shutdown After Encode ähnelt.
        /// </summary>
        public static string ToggleSwitchShutdown {
            get {
                return ResourceManager.GetString("ToggleSwitchShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use Bit-Depth from Preset? ähnelt.
        /// </summary>
        public static string ToggleSwitchUsePresetBitDepth {
            get {
                return ResourceManager.GetString("ToggleSwitchUsePresetBitDepth", resourceCulture);
            }
        }
    }
}
