name: Build NEAV1E V2

on: [ push, workflow_dispatch ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore
      run: nuget restore
      
    - name: Build
      run: dotnet publish -r win-x64 --configuration Release

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
       # Artifact name
       name: Build
       # A file, directory or wildcard pattern that describes what to upload
       path: 'NotEnoughAV1Encodes\bin\Release\net5.0-windows\win-x64\publish\'
